### PR TITLE
Hide your own organization in search endpoint

### PR DESCRIPTION
**Pull request by dmeijboom**
Closes: #81

### CODE REVIEW

**Review by stevenvegt — CHANGES_REQUESTED** [review]
Not sure how this endpoint will be used, but I can imagine it's not only for finding other organizations. Perhaps add an `omitSelf` flag to the `searchParams`?

**Comment by reinkrul** [comment]
> Not sure how this endpoint will be used, but I can imagine it's not only for finding other organizations. Perhaps add an `omitSelf` flag to the `searchParams`?

It's only for finding eOverdracht receiver orgranizations (currently), so I'd say fine for now? YAGNI

**Review by reinkrul — APPROVED** [review]

**Comment by stevenvegt** [comment]
Than I would like to suggest to add this new behaviour to the api.yaml description on line 443.

**Comment by dmeijboom** [comment]
> Than I would like to suggest to add this new behaviour to the api.yaml description on line 443.

Done!

**Review by stevenvegt — APPROVED** [review]

**Pull request merged**
